name: Uniswap V3 Indexer
contracts:
  - name: UniswapV3Factory
    abi_file_path: src/abis/factoryAbi.json
    handler: src/EventHandlerFactory.ts
    events:
      - event: PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
        isAsync: true
  - name: UniswapV3Pool
    abi_file_path: src/abis/poolAbi.json
    handler: src/EventHandlerPools.ts
    events:
      - event: Burn(address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
        isAsync: true
      - event: Collect(address indexed owner, address recipient, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount0, uint128 amount1)
        isAsync: true
      - event: Initialize(uint160 sqrtPriceX96, int24 tick)
        isAsync: true
      - event: Mint(address sender, address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
        isAsync: true
      - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
        isAsync: true
networks:
  # - id: 1
  #   start_block: 0
  #   contracts:
  #     - name: UniswapV3Factory
  #       address:
  #         - 0x1F98431c8aD98523631AE4a59f267346ea31F984
  #     - name: UniswapV3Pool
  #       address:
  - id: 8453
    start_block: 1371670
    contracts:
      - name: UniswapV3Factory
        address:
          - 0x33128a8fC17869897dcE68Ed026d694621f6FDfD
      - name: UniswapV3Pool
        address:
